{% set name = "fwlite" %}
{% set version = "11.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/gartung/fwlite/archive/{{ version }}.tar.gz
    sha256: 4bf2a90bfbc9bc169090563cd1a70436260c164cd1091c62155df124a5962a8e
    folder: src
  - url: https://github.com/cms-data/Fireworks-Geometry/archive/V07-06-00.tar.gz
    sha256: 93312e7c60525c66c09c86fdc36db401c281b95ccb2d9195d735f84506f5868b
    folder: data/Fireworks/Geometry/data
  - url: https://github.com/cms-data/DataFormats-PatCandidates/archive/V01-00-01.tar.gz
    sha256: 5a0941df5a191d0f942e26838103659970ba29cb9cd4ab3d0cc45bcc01b408df
    folder: data/DataFormats/PatCandidates/data
  - url: http://cmsshow-rels.web.cern.ch/cmsShow-rels/samples/11_0/RelValTTbarLepton_MINIAOD.root
    sha256: 6edb4763a38ee13dca037fa8898720af5421790a789b6e9b2af516448005a133
    folder: data
  - url: http://cmsshow-rels.web.cern.ch/cmsShow-rels/samples/11_0/RelValZpMM_RECO.root
    sha256: d4c79e4549dfb37d1111240fa3c1ae001f7ed10a6487215fb81fd0b197374f2e
    folder: data

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - git
    - sed
    # Required for OpenGL support
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#libgl
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - boost-cpp 
    - clhep =2.4.0.2
    - cms-md5
    - hepmc2
    - libsigcpp
    - sigcpp-2.0
    - libuuid
    - libjpeg-turbo
    - pybind11
    - python
    - root
    - root_base
    - root-binaries
    - root-dependencies
    - tbb
    - tbb-devel
    - tinyxml2
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xz
    - zlib
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('clhep', max_pin='x.x.x.x') }}
    - cms-md5
    - hepmc2
    - libsigcpp
    - libjpeg-turbo
    - python
    - root
    - root_base
    - root-binaries
    - root-dependencies
    - tbb
    - tbb-devel
    - tinyxml2
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xz
    - zlib

  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
    commands:
      - ldd ${CONDA_PREFIX}/bin/cmsShow.exe  # [linux]
      - otool -L ${CONDA_PREFIX}/bin/cmsShow.exe  # [osx]
      - xvfb-run -s '-screen 0 1024x768x24' cmsShow.exe --soft --help  # [linux]
      - cmsShow.exe --help  # [osx]

about:
  home: http://cms-sw.github.io/cmssw
  summary: "Fireworks is the event display application for the CMS Experiment"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gartung
    - chrisburr
