{% set name = "fwlite" %}
{% set version = "11.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/gartung/fwlite/archive/{{ version }}.tar.gz
    sha256: 106e62e9700efbd6005ac117dae2ef5a347010e7ab84492f74e8af14c58c210c
    folder: src
  - url: https://github.com/cms-data/Fireworks-Geometry/archive/V07-06-00.tar.gz
    sha256: 93312e7c60525c66c09c86fdc36db401c281b95ccb2d9195d735f84506f5868b
    folder: data/Fireworks/Geometry/data
  - url: https://github.com/cms-data/DataFormats-PatCandidates/archive/V01-00-01.tar.gz
    sha256: 5a0941df5a191d0f942e26838103659970ba29cb9cd4ab3d0cc45bcc01b408df
    folder: data/DataFormats/PatCandidates/data
  - url: https://cmsshow-rels.web.cern.ch/cmsShow-rels/samples/11_2/RelValZTTminiaod.root
    sha256: 4c4ddc418c7131f6eea16ea4bfefa36c2dba8ac2161640bf93b1d7889ce8fa2c
    folder: data
  - url: https://cmsshow-rels.web.cern.ch/cmsShow-rels/samples/11_2/RelVallZTTGenSimReco.root
    sha256: 209e6bda0496892d33137bf67ecb583b233e4c962154b6ca574aa33f824ea532
    folder: data
  - url: http://cmsrep.cern.ch/cmssw/download/Fireworks-Geometry/20200401/cmsGeom2026.root
    sha256: 3077e4d9abd62c57d1d71b30fa968ba52a7c12879a7fc71d90d94c4123e426fa
    folder: data/Fireworks/Geometry/data
  - url: https://github.com/gartung/cmaketools/archive/refs/tags/1.8-cms.tar.gz
    sha256: b7f7fbb210dbb9017ed6ddd6aaff61dd9dc1592c63be2f5730c86b0cb8c02285
    folder: cmaketools

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
    - pkg-config
    - sed
    - make
    # Required for OpenGL support
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#libgl
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - boost-cpp 
    - clhep =2.4.1.3
    - cms-md5
    - fmt
    - hepmc2
    - libsigcpp
    - sigcpp-2.0
    - libuuid
    - libjpeg-turbo
    - pybind11
    - python
    - root
    - tbb
    - tbb-devel
    - tinyxml2
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xz
    - zlib
    - zstd
  run:
    - {{ pin_compatible('clhep', max_pin='x.x.x.x') }}
    - cms-md5
    - hepmc2
    - libsigcpp
    - libjpeg-turbo
    - python
    - root
    - tbb
    - tbb-devel
    - tinyxml2
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxft  # [linux]
    - libgul  # [linux]
    - xz
    - zlib
    - zstd

  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
    commands:
      - ldd ${CONDA_PREFIX}/bin/cmsShow.exe  # [linux]
      - otool -L ${CONDA_PREFIX}/bin/cmsShow.exe  # [osx]
      - xvfb-run -s '-screen 0 1024x768x24' cmsShow.exe --soft --help  # [linux]
      - cmsShow.exe --help  # [osx]

about:
  home: http://cms-sw.github.io/cmssw
  summary: "Fireworks is the event display application for the CMS Experiment"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gartung
    - chrisburr
