{% set name = "fwlite" %}
{% set version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/gartung/fwlite/archive/{{ version }}.tar.gz
    sha256: f51bb0c55262399eddc72f6b34aa135257074e8dd76c283b13d2d46f0aa596e8
    folder: src
  - url: https://github.com/cms-data/Fireworks-Geometry/archive/V07-05-04.tar.gz
    sha256: 741dd882851b8d1715a0e299da904fec75b4e5eb35b021d12f6536214b77566b
    folder: data/Fireworks/Geometry/data
  - url: https://github.com/cms-data/DataFormats-PatCandidates/archive/V01-00-01.tar.gz
    sha256: 5a0941df5a191d0f942e26838103659970ba29cb9cd4ab3d0cc45bcc01b408df
    folder: data/DataFormats/PatCandidates/data
  - url: http://cmsshow-rels.web.cern.ch/cmsShow-rels/samples/11/RelValTTBarReco.root
    sha256: bf4640565f9dc1c29bd52a406ab937145720bf1f26a25e4216a2453c53d140d5
    folder: data
  - url: http://cmsshow-rels.web.cern.ch/cmsShow-rels/samples/11/RelValTTMiniaod.root
    sha256: cfaaef76a5c56138af429ce4304cfef8c6c272e66417d12ca7169cb44ab97aaf
    folder: data

build:
  number: 5
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - git
    - sed
    # Required for OpenGL support
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#libgl
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - boost-cpp 
    - clhep =2.4.0.2
    - cms-md5
    - hepmc2
    - libsigcpp
    - libuuid
    - libjpeg-turbo
    - pybind11
    - python
    - root
    - root_base
    - root-binaries
    - root-dependencies
    - tbb
    - tbb-devel
    - tinyxml2
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xz
    - zlib
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('clhep', max_pin='x.x.x.x') }}
    - cms-md5
    - hepmc2
    - libsigcpp
    - libjpeg-turbo
    - python
    - root
    - root_base
    - root-binaries
    - root-dependencies
    - tbb
    - tbb-devel
    - tinyxml2
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xz
    - zlib

  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
    commands:
      - ldd ${CONDA_PREFIX}/bin/cmsShow.exe  # [linux]
      - otool -L ${CONDA_PREFIX}/bin/cmsShow.exe  # [osx]
      - xvfb-run -s '-screen 0 1024x768x24' cmsShow.exe --soft --help  # [linux]
      - cmsShow.exe --help  # [osx]

about:
  home: http://cms-sw.github.io/cmssw
  summary: "Fireworks is the event display application for the CMS Experiment"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gartung
    - chrisburr
