travis:
  secure:
    BINSTAR_TOKEN: YuD1eZ6ohXANtIeDugVVyf8JD/Zv3jsPwFE+3M9541MV+w2mYHtdNuCkGPPEZrH7K6GEQd3PWm7erOwChCKVJuFYqoKnx+o+2qxycgDGlR0iKPXkU0hImehSkiQkPXl33NbxpfusE2KVespwvkueSoMwUl4XrwdAO8VUOMebjGH5K5IacWwCVk2rhTknVB8//9XZRtVWU7yoHgTtKUekviPxu0TF9wauCi5Q2q94QKxYEOWW+OxvvjAVei0zt5qrePpglbbXxMW1zr8zgk6BDF5cWkZkPEvv8iamliINBEkpuVfNg/Ul2hPqO2xLRxM036Aao3HnMgODcV9irkOW2he70Rj4FW7EpL6MX9u2gpNDjqHdIFz4dspm292YaWWw5JmkQmhKXfKU+wGlgqLouh0xUXbjLw9v5AbyEl2r3wrJAFLRMwaLWWYzqHWfXq6RoqWkfufAA6DglAgTJaNpJdzd3ykV1Pvc8IhGptDUsQQuQaxY9xoU1LmrckUTlFn3uKpIUtzNoBt1Cn1BVb664alsC6gwo9zip3ESTSxqLA1WlAMIBO1a43I2lr305Oc9W+QpIgVc2Vwu09UNsUg1bQhvrQjqMX6/tBTJPT8plTrw+u4tlYqWFRA6Qzd8uO2Bm/PMc+cENDx8I7WilXe+kiuoFqNTbHv9+NpvzhSRNq0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
